// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using System.Runtime.CompilerServices;
using Entities=WPAppStudio.Entities;
using RepositoriesBase=WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// Geography_Html data source.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public class Geography_Geography : IGeography_Geography 
    {        
        /// <summary>
        /// Retrieves the html content.
        /// </summary>
        /// <returns>A string with the content in html format.</returns>
        public string Get()
        {			
            return @"<div><b />Lake Chabot lies at the north of Castro Valley. Directly to the west is San Leandro. Hayward is to the south. To the east, the closest cities are San Ramon, Dublin and Pleasanton. The San Leandro Hills extend along the northeastern edge of the community.<br /><br /></div><div>The eastern hills of Castro Valley constitute the headwaters of the San Lorenzo Creek watershed and the origin of several creeks that flow into San Lorenzo Creek: Bolinas, Castro Valley, Chabot, Crow, Cull, Eden, Hollis, Kelly Canyon, Norris, and Palomares creeks.</div>";
        }
	}
}
