// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using System.Runtime.CompilerServices;
using Entities=WPAppStudio.Entities;
using RepositoriesBase=WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// historywiki_Html data source.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public class History_historywiki : IHistory_historywiki 
    {        
        /// <summary>
        /// Retrieves the html content.
        /// </summary>
        /// <returns>A string with the content in html format.</returns>
        public string Get()
        {			
            return @"<div>Before the arrival of European settlers the area was settled by the Chocheño (also spelled Chochenyo or Chocenyo) subdivision of the Ohlone Native Americans.</div><div>With the arrival of Europeans, Castro Valley was part of the land granted to Mission San Jose in 1797. The area Castro Valley now occupies was part of the extensive colony of New Spain in what was the state of Alta California.</div><div>Castro Valley was part of the original 28,000 acre (110 km²) land grant given to Castro, called Rancho San Lorenzo. This land grant included Hayward, San Lorenzo, and Castro Valley, including Crow Canyon, Cull Canyon, and Palomares Canyons. Castro had a gambling habit and had to sell off portions of his land to pay gambling debts. The last of his holding was sold in a sheriff's sale in 1864 to Faxon Atherton for $400,000.</div><div>Atherton (after whom the city of Atherton is named) in turn began selling off his portion in smaller parcels. Two gentlemen named Cull (the namesake of Cull Canyon) and Luce bought some 2,400 acres (10 km²) and began running a steam-operated saw mill in Redwood Canyon. The Jensen brothers also bought land from Atherton in 1867.</div><div>During the 1940s and 1950s, Castro Valley was known for its chicken ranches. Later it developed into a bedroom community, where workers live and commute to their jobs in the surrounding communities.</div>";
        }
	}
}
