// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using System.Runtime.CompilerServices;
using Entities=WPAppStudio.Entities;
using RepositoriesBase=WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// info_Html data source.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public class Info_info : IInfo_info 
    {        
        /// <summary>
        /// Retrieves the html content.
        /// </summary>
        /// <returns>A string with the content in html format.</returns>
        public string Get()
        {			
            return @"<div>Castro Valley is a census-designated place (CDP) in Alameda County, California, United States. As of the 2000 census, it is the fifth most populous unincorporated area in California, and the twenty-third in the United States. The population was 61,388 at the 2010 census.</div><div>Castro Valley is named after Don Guillermo Castro, who was a soldier in the Mexican army and a rancher.</div><div>First known for chicken ranches, Castro Valley eventually became a bedroom community.</div>";
        }
	}
}
