// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using System.Runtime.CompilerServices;
using Entities=WPAppStudio.Entities;
using RepositoriesBase=WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// SpecialPlaces_specialplacesCollection data source.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public class SpecialPlaces_specialplacesCollection : ISpecialPlaces_specialplacesCollection 
    {
		private const int MaxResults = 10;
        private readonly ObservableCollection<Entities.specialplacesCollectionSchema> _data = new ObservableCollection<Entities.specialplacesCollectionSchema>
		{
          new Entities.specialplacesCollectionSchema
            {
                Id= new Guid("eabacde4-ba93-4b92-be59-82aceadbe46c"),
                Title=@"Castro Valley High School",
                Subtitle=@"19400 Santa Maria Ave",
                Image=@"..\Images\Item-7fefbce6-defb-4929-86d1-c99ea5d6196d.jpg",
                Description=@"A comprehensive, 9-12 public high school located in an unincorporated suburban community in the San Francisco Bay Area. ",
			},
          new Entities.specialplacesCollectionSchema
            {
                Id= new Guid("ed3dc758-930b-4fff-8b05-9ff795ba9ee5"),
                Title=@"Castro Village Bowl",
                Subtitle=@"3501 Village Dr.",
                Image=@"..\Images\Item-340de893-e126-413e-bd4b-0ebc2c740edd.jpg",
                Description=@"32 Lanes of automatic scoring
Bumpers for children under 7 years of age
Full service Cocktail Lounge and Snack Bar
Leagues available for all ages
Birthday parties for kids",
			},
          new Entities.specialplacesCollectionSchema
            {
                Id= new Guid("77c14195-dd45-4b9f-b17e-cd2af43341ce"),
                Title=@"Chabot Cinema",
                Subtitle=@"2853 Castro Valley Blvd",
                Image=@"..\Images\Item-c482a824-9b9f-45a6-bb57-19fd0a8d3214.jpg",
                Description=@"All shows before 6pm are $5.50 http://www.cineluxtheatres.com/loc_chabot.asp",
			},
          new Entities.specialplacesCollectionSchema
            {
                Id= new Guid("ce07ffca-7d19-4bab-b1d2-af14580c6aa4"),
                Title=@"Cull Canyon",
                Subtitle=@"18627 Cull Canyon Rd",
                Image=@"..\Images\Item-7e272eaa-414c-4408-9a6d-2278c6dafd7d.jpg",
                Description=@"This popular Castro Valley swimming spot is only a short drive north from Interstate 580 on Cull Canyon Road in Castro Valley. When the swim area was constructed, a secondary dam was built to provide an inner swimming area complete with sandy beach. Never previously tried, this innovation made the swim area water level independent of the reservoir's, unaffected by summer draw-downs.",
			},
          new Entities.specialplacesCollectionSchema
            {
                Id= new Guid("70d87987-7294-43ff-a9de-3a905f014f8f"),
                Title=@"Golden Tee Golfland",
                Subtitle=@"2533 Castro Valley Blvd",
                Image=@"..\Images\Item-e55a9084-b40f-4874-be21-5a8b7a40445f.jpg",
                Description=@"Family fun in Castro Valley! Golfland offers world class mini golf as well as a video game arcade. Perfect for your next birthday party or group event!",
			},
          new Entities.specialplacesCollectionSchema
            {
                Id= new Guid("2257f0dc-f552-4750-bd50-339c59c2d2e8"),
                Title=@"Lake Chabot Regional Park ",
                Subtitle=@"17930 Lake Chabot Rd",
                Image=@"..\Images\Item-85d117f2-ad55-4cfe-850a-33165b53f660.jpg",
                Description=@"Lake Chabot Reservoir was built in 1874-75 as a primary source of water for the East Bay. The 315-acre lake was closed to recreation for 91 years. Legislation passed in the 1960s opened the lake for controlled recreational uses. Currently, the lake serves as a standby emergency water supply. For this reason, visitors are asked to observe certain necessary regulations to keep the waters pure. ",
			},
          new Entities.specialplacesCollectionSchema
            {
                Id= new Guid("0b269167-316b-45cf-8ed4-61933ce232b9"),
                Title=@"Willow Park Public Golf Course",
                Subtitle=@"17007 Redwood Rd",
                Image=@"..\Images\Item-b23e7d06-1540-4b96-b219-609dc05cf222.jpg",
                Description=@"Willow Park Golf Course is celebrated as one of the Bay Area’s finest and enjoyable golf destinations. Located in Castro Valley, the 18 hole golf facility is nestled away among the rolling hills of the east bay & is home to some of the most beautiful golf scenery in Northern California. Completely surrounded by breathtaking natural wild life including the San Leandro creek which comes into play on nearly every hole, the course offers some of the most unique golf around & is truly enjoyable for golfers of all levels.",
			},
		};
	
		
        /// <summary>
        /// Retrieves the data from a static data source, in an observable collection of specialplacesCollectionSchema items.
        /// </summary>
        /// <returns>An observable collection of specialplacesCollectionSchema items.</returns>
        public ObservableCollection<Entities.specialplacesCollectionSchema> GetData(int numPage)
        {								
			return new ObservableCollection<Entities.specialplacesCollectionSchema>(_data.Skip(MaxResults * numPage).Take(MaxResults));
        }
		
		/// <summary>
        /// Retrieves the data from a static data source, filtered by a filter specification, in an observable collection of specialplacesCollectionSchema items.
        /// </summary>
		/// <param name="filter">Filter operation specification</param>
        /// <returns>An observable collection of specialplacesCollectionSchema items.</returns>
        public ObservableCollection<Entities.specialplacesCollectionSchema> Search(FilterSpecification filter)
        {
            return RepositoriesBase.Filter<Entities.specialplacesCollectionSchema>.FilterCollection(filter, _data);
        }
	}
}
