// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows.Input;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// SpecialPlaces_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface ISpecialPlaces_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentspecialplacesCollectionSchema property.
        /// </summary>
		Entities.specialplacesCollectionSchema CurrentspecialplacesCollectionSchema { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechSpecialPlaces_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechSpecialPlaces_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareSpecialPlaces_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareSpecialPlaces_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartSpecialPlaces_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartSpecialPlaces_DetailStaticControlCommand { get; }

	}
}
