// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSchema.tt
using System;
using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;
using WPAppStudio.Entities.Base;

namespace WPAppStudio.Entities
{
    /// <summary>
    /// Implementation of the StatisticsSchema Data Schema.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public class StatisticsSchema : BindableBase
    {
	    /// <summary>
        /// Identifier for instances created according StatisticsSchema Data Schema.
        /// </summary>
		public Guid Id { get; set; }

        private string _title;

        /// <summary>
        /// Gets/Sets value of Title column.
        /// </summary>
        public string Title
        {
            get { return _title; }
            set
            {
                SetProperty(ref _title, value);
            }
        }

        private string _description;

        /// <summary>
        /// Gets/Sets value of Description column.
        /// </summary>
        public string Description
        {
            get { return _description; }
            set
            {
                SetProperty(ref _description, value);
            }
        }
    }
}
