// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows.Input;
using Controls=WPAppStudio.Controls;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;
using IServices=WPAppStudio.Services.Interfaces;
using IViewModels=WPAppStudio.ViewModel.Interfaces;
using Localization=WPAppStudio.Localization;
using Repositories=WPAppStudio.Repositories;
using Services=WPAppStudio.Services;
using ViewModelsBase=WPAppStudio.ViewModel.Base;
using WPAppStudio;
using WPAppStudio.Shared;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of Statistics_Detail ViewModel.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class Statistics_DetailViewModel : EntitiesBase.BindableBase, IViewModels.IStatistics_DetailViewModel, ViewModelsBase.INavigable
    {       

		private readonly IServices.IDialogService _dialogService;
		private readonly IServices.INavigationService _navigationService;
		private readonly IServices.ISpeechService _speechService;
		private readonly IServices.IShareService _shareService;
		private readonly IServices.ILiveTileService _liveTileService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="Statistics_DetailViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="speechService">The Speech Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        public Statistics_DetailViewModel(IServices.IDialogService dialogService, IServices.INavigationService navigationService, IServices.ISpeechService speechService, IServices.IShareService shareService, IServices.ILiveTileService liveTileService)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_speechService = speechService;
			_shareService = shareService;
			_liveTileService = liveTileService;
        }
		
		private Entities.StatisticsSchema _currentStatisticsSchema;

        /// <summary>
        /// CurrentStatisticsSchema property.
        /// </summary>		
        public Entities.StatisticsSchema CurrentStatisticsSchema
        {
            get
            {
				return _currentStatisticsSchema;
            }
            set
            {
                SetProperty(ref _currentStatisticsSchema, value);
            }
        }

        /// <summary>
        /// Delegate method for the TextToSpeechStatistics_DetailStaticControlCommand command.
        /// </summary>
        public  void TextToSpeechStatistics_DetailStaticControlCommandDelegate() 
        {
	
				_speechService.TextToSpeech(CurrentStatisticsSchema.Description + " " + CurrentStatisticsSchema.Description);
        }
		

        private ICommand _textToSpeechStatistics_DetailStaticControlCommand;

        /// <summary>
        /// Gets the TextToSpeechStatistics_DetailStaticControlCommand command.
        /// </summary>
        public ICommand TextToSpeechStatistics_DetailStaticControlCommand
        {
            get { return _textToSpeechStatistics_DetailStaticControlCommand = _textToSpeechStatistics_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(TextToSpeechStatistics_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the ShareStatistics_DetailStaticControlCommand command.
        /// </summary>
        public  void ShareStatistics_DetailStaticControlCommandDelegate() 
        {
	
				_shareService.Share(CurrentStatisticsSchema.Description,CurrentStatisticsSchema.Description);
        }
		

        private ICommand _shareStatistics_DetailStaticControlCommand;

        /// <summary>
        /// Gets the ShareStatistics_DetailStaticControlCommand command.
        /// </summary>
        public ICommand ShareStatistics_DetailStaticControlCommand
        {
            get { return _shareStatistics_DetailStaticControlCommand = _shareStatistics_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(ShareStatistics_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartStatistics_DetailStaticControlCommand command.
        /// </summary>
        public  void PinToStartStatistics_DetailStaticControlCommandDelegate() 
        {
	
				_liveTileService.PinToStart(typeof(IViewModels.IStatistics_DetailViewModel), CreateTileInfoStatistics_DetailStaticControl());
        }
		

        private ICommand _pinToStartStatistics_DetailStaticControlCommand;

        /// <summary>
        /// Gets the PinToStartStatistics_DetailStaticControlCommand command.
        /// </summary>
        public ICommand PinToStartStatistics_DetailStaticControlCommand
        {
            get { return _pinToStartStatistics_DetailStaticControlCommand = _pinToStartStatistics_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(PinToStartStatistics_DetailStaticControlCommandDelegate); }
        }
		public object NavigationContext
        {
            set
            {              
                if (!(value is Entities.StatisticsSchema)) { return; }
                
                CurrentStatisticsSchema = value as Entities.StatisticsSchema;
            }
        }
        /// <summary>
        /// Initializes a <see cref="Services.TileInfo" /> object for the Statistics_DetailStaticControl control.
        /// </summary>
		/// <returns>A <see cref="Services.TileInfo" /> object.</returns>
        public Services.TileInfo CreateTileInfoStatistics_DetailStaticControl()
        {
            var tileInfo = new Services.TileInfo
            {
                CurrentId = CurrentStatisticsSchema.Id.ToString(),
                Title = CurrentStatisticsSchema.Description,
                BackTitle = CurrentStatisticsSchema.Description,
                BackContent = CurrentStatisticsSchema.Description,
                Count = 0,
                BackgroundImagePath = string.Empty,
                BackBackgroundImagePath = string.Empty,
                LogoPath = "Logo-4ff76cb8-5c06-4bf6-bcdc-64756a06d71a.png"
            };
            return tileInfo;
        }
    }
}
