// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ServiceLocator.tt
using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;
using IIoc=WPAppStudio.Ioc.Interfaces;
using Ioc=WPAppStudio.Ioc;
using IViewModels=WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.Services
{
    /// <summary>
    /// Implementation of the ViewModel locator service based on IoC.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public class ViewModelLocatorService
    {
        // IoC container
        private readonly IIoc.IContainer _container;

        /// <summary>
        /// Initializes a new instance of the <see cref="ViewModelLocatorService" /> class.
        /// </summary>
        public ViewModelLocatorService()
        {
            _container = new Ioc.Container();
        }

        /// <summary>
        /// Gets the reference to a Info_InfoViewModel.
        /// </summary>
		public IViewModels.IInfo_InfoViewModel Info_InfoViewModel
        {
            get { return _container.Resolve<IViewModels.IInfo_InfoViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a Statistics_DetailViewModel.
        /// </summary>
		public IViewModels.IStatistics_DetailViewModel Statistics_DetailViewModel
        {
            get { return _container.Resolve<IViewModels.IStatistics_DetailViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a SpecialPlaces_DetailViewModel.
        /// </summary>
		public IViewModels.ISpecialPlaces_DetailViewModel SpecialPlaces_DetailViewModel
        {
            get { return _container.Resolve<IViewModels.ISpecialPlaces_DetailViewModel>(); }
        }
		/// <summary>
        /// Gets the reference to a AboutViewModel.
        /// </summary>
		public IViewModels.IAboutViewModel AboutViewModel
        {
            get { return _container.Resolve<IViewModels.IAboutViewModel>(); }
        }
		
		/// <summary>
        /// Gets the reference to a LicenseViewModel.
        /// </summary>
		public IViewModels.ILicenseViewModel LicenseViewModel
        {
            get { return _container.Resolve<IViewModels.ILicenseViewModel>(); }
        }
    }
}
